- name: Register RHEL instances with Red Hat subscription
  hosts: rhel_instances
  vars_files:
    - ../vault.yml
  tasks:
    - name: Register systems with Red Hat
      community.general.redhat_subscription:
        state: present
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
        auto_attach: true
