---
# handlers file for ansible/roles/lamp

- name: Apply SELinux context
  command: restorecon -R /var/www/html
  listen: Apply SELinux context

- name: Restart Apache
  service:
    name: httpd
    state: restarted
  listen: Restart Apache