all:
  children:
    rhel_instances:
      hosts:
        instance_1:
          ansible_host: "3.8.115.251"
        instance_2:
          ansible_host: "18.171.161.137"
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /Users/sunny/Desktop/awskey.pem